version: '3'
services:
  web:
    image: nginx:1.15.6
    ports:
      - "8080:80"
    depends_on: # 追加
      - app
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  app:
    build: ./docker/php
    volumes:
     - .:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: todolist
      MYSQL_USER: misaki
      MYSQL_PASSWORD: misaki
      MYSQL_ROOT_PASSWORD: misaki
    ports:
            - "127.0.0.1:3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/mysql_init:/docker-entrypoint-initdb.d

volumes:
    mysql-data:
            #       external:
            #           name: project-mysql
            #

                   #      phpmyadmin:
                   #        image: phpmyadmin/phpmyadmin
                   #        environment:
                   #          - PMA_ARBITRARY= 1
                   #          - PMA_HOST= mysql
                   #          - PMA_USER= root
                   #          - PMA_PASSWORD= misaki
                   #        ports:
                   #                - "127.0.0.1:3000:3306"
                   #        volumes:
                   #          - ./db/phpmyadmin:/sessions
                   #    
